# Docker Compose version v2.29.7
services:
  tlv:
    image: tlv
    build: .
    volumes:
      - /DATA/evanstefan/TinyLLaVA-Video/data:/app/data:ro
      - ./checkpoints:/app/checkpoints:ro
    # - output:/app/output
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1', '2', '3' ]
              capabilities: [ gpu ]
# volumes:
#   output:
